"""Human descriptions of analysis flags (mail, url, attachment, sender) for tooltips and reports."""
from __future__ import annotations

FLAGS: dict[str, str] = {
    "trusted_sender": "Known notification/SaaS relay with passing authentication, or a sender on this case's trusted list. Risk is capped unless strong indicators are present.",
    # authentication
    "spf_fail": "SPF check failed or soft-failed: the sending server is not authorised for the envelope domain.",
    "spf_none": "No SPF record / result for the sender domain.",
    "dkim_fail": "DKIM signature failed verification (content altered or forged signature).",
    "dkim_none": "Message is not DKIM signed.",
    "dmarc_fail": "DMARC failed: neither SPF nor DKIM aligned with the From domain.",
    "dmarc_none": "No DMARC policy / result.",
    "compauth_fail": "Microsoft composite authentication failed (Exchange Online).",
    "dkim_domain_unaligned": "DKIM signing domain differs from the From domain.",
    "spf_domain_unaligned": "SPF (envelope) domain differs from the From domain.",
    # sender consistency
    "returnpath_mismatch": "Return-Path domain differs from the From domain (bounce address elsewhere).",
    "sender_mismatch": "Sender header domain differs from From.",
    "replyto_mismatch": "Reply-To goes to another domain than From: replies are diverted.",
    "replyto_webmail": "Reply-To is a free webmail address (typical BEC / advance-fee fraud).",
    "email_in_display_name": "The display name itself contains an e-mail address.",
    "display_name_email_mismatch": "The display name shows an e-mail address that is not the real sender address (address spoofing trick).",
    "mixed_script_display_name": "Display name mixes Latin with Cyrillic/Greek characters (homoglyph trick).",
    "from_webmail": "Sender uses a free webmail provider.",
    "helo_domain_mismatch": "Originating server HELO name does not match the sender domain and has no reverse DNS (not raised when SPF passes or the host is a known mail platform).",
    "exchange_internal": "Accepted by Exchange as an authenticated submission from a tenant user (X-MS-Exchange-Organization-AuthAs: Internal). Intra-tenant mail is neither DKIM-signed nor DMARC-evaluated, so those 'none' results are ignored.",
    "gateway_spam_verdict": "The receiving gateway classified the message as spam or phishing (Exchange SCL >= 5, or SFV:SPM/BLK).",
    "gateway_bulk_verdict": "The receiving gateway classified the message as bulk mail (Exchange BCL >= 4).",
    "calendar_item": "Calendar object (appointment, meeting request or response) rather than a mail message.",
    "scripted_mailer": "Sent with a scripting-library mailer (PHPMailer…) by an authenticated or bulk sender: how CMS newsletters are sent. Only unauthenticated use is flagged suspicious_mailer.",
    "tracker_redirect": "Link goes through an e-mail service provider's click tracker (opaque redirect), so the anchor text cannot match the href.",
    "own_domain": "Link stays on the authenticated sender's own domain: credential wording, redirects and text/href differences there are the sender's navigation, not a lure.",
    "sender_punycode": "Sender domain is an internationalised (xn--) domain, often used for homoglyph lookalikes.",
    "sender_mixed_script": "Sender domain mixes scripts (e.g. Cyrillic 'a' in a Latin domain).",
    "sender_confusable": "Sender domain contains characters confusable with others.",
    "sender_lookalike_internal": "Sender domain imitates one of the organisation's own domains.",
    "sender_lookalike_brand": "Sender domain imitates a well-known brand.",
    "sender_tld_swap": "Same domain name as a reference with a different TLD.",
    "sender_subdomain_trick": "The reference domain appears as a subdomain of an unrelated domain.",
    "sender_homoglyph": "Domain looks like the reference after homoglyph normalisation.",
    "sender_digit_substitution": "Letters replaced by look-alike digits (0/o, 1/l).",
    "sender_edit_distance": "Domain is one or two characters away from a reference domain (typosquatting).",
    "sender_brand_embedding": "Reference name embedded with an extra token (paypal-secure, interne-login).",
    "replyto_lookalike_internal": "Reply-To domain imitates an internal domain.",
    "replyto_lookalike_brand": "Reply-To domain imitates a brand.",
    # headers
    "no_message_id": "Missing Message-ID header (bulk tools / forged mails).",
    "malformed_message_id": "Message-ID is malformed.",
    "message_id_domain_mismatch": "Message-ID domain differs from the sender domain.",
    "no_date": "Missing Date header.",
    "date_skew": "Date header is more than 6 hours away from the first Received timestamp.",
    "received_time_travel": "Received chain timestamps go backwards (forged headers or clock issues).",
    "no_received": "No Received headers at all (locally generated or stripped).",
    "single_hop": "Only one Received header.",
    "no_origin_ip": "Could not determine an originating public IP.",
    "suspicious_mailer": "X-Mailer / User-Agent typical of scripts or mass-mailing tools.",
    "bulk_mailer": "Sent through a bulk e-mail service.",
    "high_priority": "Marked high priority / urgent.",
    "unsubscribe_without_list": "List-Unsubscribe header without List-Id.",
    "undisclosed_recipients": "No visible recipients (To/Cc empty).",
    "mass_recipients": "More than 30 recipients.",
    # body
    "lexicon_urgency": "Urgency / pressure wording.",
    "lexicon_financial": "Payment, invoice, bank details wording.",
    "lexicon_gift_card": "Gift card / prepaid card wording (classic scam).",
    "lexicon_credentials": "Password / login / verification code wording.",
    "lexicon_authority": "Impersonation of authority (CEO, IT, bank, police...).",
    "lexicon_secrecy": "Requests for confidentiality / discretion.",
    "lexicon_availability": "'I am in a meeting, cannot call' style excuses (BEC).",
    "lexicon_delivery": "Parcel / delivery lure.",
    "lexicon_document_lure": "Shared document / voicemail / fax lure.",
    "bec_pattern": "Combination typical of Business Email Compromise: authority + money + urgency/secrecy.",
    "credential_phishing_pattern": "Credential wording combined with urgency.",
    "zero_width_chars": "Zero-width characters inside the text (filter evasion).",
    "bidi_override": "Unicode bidirectional override characters (text/filename disguise).",
    "hidden_text": "Substantial text hidden with CSS (font-size 0, white on white, display none) - content salting.",
    "hidden_preheader": "Short hidden preview text at the top of the body - standard in marketing / notification mail, informational.",
    "hidden_style": "An element's inline style hides content (display:none, zero font size, white-on-white, off-screen).",
    "base64_blob": "Large base64 blob in the body.",
    "obfuscated_html": "Escaped / obfuscated HTML sequences.",
    "html_script": "Script tag inside the mail body.",
    "html_form": "HTML form inside the mail body.",
    "html_form_password": "Form with a password field inside the mail.",
    "html_form_external": "Form posting to an external URL.",
    "html_embed": "iframe / object / embed inside the body.",
    "image_only": "Body is essentially an image (text-filter evasion).",
    "mixed_script_text": "Visible text mixes Latin and Cyrillic/Greek letters.",
    "no_body": "Empty body.",
    "html_only": "HTML body without a plain-text alternative.",
    "empty_subject": "Empty subject.",
    "reply_without_thread": "Subject starts with RE/FW but there is no thread reference (fake reply).",
    "many_attachments": "More than 10 attachments.",
    "encrypted_body": "S/MIME encrypted content.",
    # urls
    "url_ip_literal": "Link to a raw IP address instead of a domain.",
    "url_private_ip": "Link to a private / internal IP.",
    "url_punycode": "Internationalised domain (xn--) in a link.",
    "url_suspicious_tld": "Top-level domain frequently abused (.zip, .top, .xyz...).",
    "url_many_subdomains": "Deep subdomain chain (brand.hidden.in.subdomains.example).",
    "url_shortener": "URL shortener hides the destination.",
    "url_file_hosting": "Link to a file-sharing / cloud storage service.",
    "url_free_hosting": "Link to free hosting / form builders / tunnels often used for phishing pages.",
    "url_many_hyphens": "Host with many hyphens.",
    "url_long_host": "Very long host name.",
    "url_userinfo": "user@ before the host - the real destination is after the @.",
    "url_unusual_port": "Non-standard port.",
    "url_long_url": "Very long URL.",
    "url_double_encoded": "Double URL-encoding.",
    "url_executable_download": "Link points to an executable / archive / macro document.",
    "url_credential_keywords": "Path contains login / verify / account style keywords.",
    "url_email_in_url": "Recipient e-mail embedded in the URL (personalised phishing page).",
    "url_base64_in_url": "Base64 payload in the URL.",
    "url_open_redirect": "Looks like an open-redirect parameter (redirect=https://...).",
    "url_text_href_mismatch": "Visible link text shows a different domain than the real destination.",
    "url_tracking_pixel": "1x1 tracking image.",
    "url_tracking": "Tracking parameters.",
    "url_form_action": "URL is a form target.",
    "url_meta_refresh": "Meta-refresh redirect.",
    "url_data_uri": "data: URI (inline payload).",
    "url_script_uri": "javascript: / vbscript: URI.",
    "url_file_uri": "file:// URI.",
    "url_was_defanged": "URL was already defanged in the source (hxxp / [.]).",
    "url_rewritten": "Link was wrapped by an e-mail security gateway (Safe Links, Proofpoint...); the analysed URL is the unwrapped destination.",
    "url_login_link": "Link path mentions login / account / invoice wording on an otherwise unsuspicious URL (informational).",
    "url_form_saas": "Link to a mainstream form / survey service (Microsoft Forms, Google Forms...). Common in corporate mail, occasionally abused for phishing.",
    "internal_spoof": "The From domain is one of the organisation's own domains but authentication failed - direct spoofing of the company domain.",
    # attachments (prefixed att_ at mail level)
    "executable": "Native executable (.exe, .scr, .dll...).",
    "installer": "Installer package (.msi, .msix, .apk...).",
    "script": "Script file (.js, .vbs, .bat, .ps1, .hta, .wsf...).",
    "shortcut": "Windows shortcut (.lnk / .url) - can launch commands.",
    "help": "Compiled help file (.chm) - can execute code.",
    "onenote": "OneNote section - can embed executables and scripts.",
    "disk_image": "Disk image (.iso/.img/.vhd) - bypasses Mark-of-the-Web.",
    "xll": "Excel add-in (.xll) - native code executed by Excel.",
    "double_extension": "Double extension (invoice.pdf.exe).",
    "rtlo_filename": "Right-to-left override in the file name disguises the real extension.",
    "padded_filename": "File name padded with spaces to hide the extension.",
    "zero_width_filename": "Zero-width characters in the file name.",
    "mixed_script_filename": "File name mixes scripts (homoglyphs).",
    "extension_mismatch": "Real content type does not match the extension.",
    "extension_mismatch_executable": "Executable / HTML content disguised under a harmless extension.",
    "office_macro": "VBA macro project present.",
    "macro_autoexec": "Macro runs automatically (AutoOpen, Document_Open, Workbook_Open...).",
    "macro_suspicious": "Suspicious macro keywords (Shell, CreateObject, PowerShell, download...).",
    "macro_ioc": "Macro contains IOCs (URLs, IPs, executable names).",
    "macro_obfuscated": "Obfuscated macro strings (hex, base64, chr chains).",
    "macro_vba_stomping": "VBA source stripped while p-code remains (VBA stomping).",
    "office_xlm": "Excel 4.0 (XLM) macro sheets.",
    "office_dde": "DDE / DDEAUTO field - executes commands without macros.",
    "office_external_template": "Remote template injection (template loaded from a URL).",
    "office_external_object": "External OLE object / frame relationship.",
    "office_external_relation": "External relationship in the OOXML package.",
    "office_remote_image": "Remote image (tracking / relationship trick).",
    "office_ole_object": "Embedded OLE object / package (can hide executables).",
    "office_activex": "ActiveX controls.",
    "office_encrypted": "Encrypted / password-protected Office document (sandbox evasion).",
    "office_iqy_remote": "Excel web query pulling remote content.",
    "csv_formula_injection": "CSV cell starting with a formula that runs commands.",
    "office_legacy": "Legacy binary Office format (can embed macros/exploits).",
    "rtf": "RTF document.",
    "rtf_object": "RTF with embedded OLE objects.",
    "rtf_equation_editor": "Equation Editor object (CVE-2017-11882 family).",
    "rtf_objupdate": "OLE object set to auto-update (exploit trigger).",
    "rtf_package": "Packager object (drops a file).",
    "pdf_javascript": "PDF contains JavaScript.",
    "pdf_auto_action": "PDF runs an action on open (/OpenAction, /AA).",
    "pdf_launch": "PDF /Launch action (executes a program).",
    "pdf_embedded_file": "PDF with embedded files.",
    "pdf_rich_media": "PDF with rich media / flash / sound.",
    "pdf_xfa": "XFA forms (historically exploited).",
    "pdf_submit_form": "PDF form submitting data to a URL.",
    "pdf_remote_goto": "Remote go-to action (external file).",
    "pdf_encrypted": "Encrypted PDF.",
    "pdf_encrypted_empty_password": "Encrypted with an empty password (filter evasion).",
    "pdf_obfuscated_names": "Obfuscated PDF names (/J#61vaScript).",
    "pdf_header_offset": "PDF header not at the start of the file.",
    "pdf_trailing_data": "Data appended after %%EOF.",
    "pdf_link_lure": "One-page PDF that is mostly a link (click-me lure).",
    "pdf_image_only": "Single-page image-only PDF.",
    "pdf_form": "PDF with form fields.",
    "pdf_parse_error": "PDF could not be parsed (malformed or intentionally broken).",
    "pdf_jbig2": "JBIG2 stream (historical exploit vector).",
    "pdf_incremental_updates": "PDF with incremental updates (content changed after signing).",
    "archive": "Archive file.",
    "encrypted_archive": "Password-protected archive (scanner evasion).",
    "archive_contains_executable": "Archive contains an executable.",
    "archive_contains_script": "Archive contains a script.",
    "archive_contains_shortcut": "Archive contains a shortcut (.lnk).",
    "archive_contains_disk_image": "Archive contains a disk image.",
    "archive_contains_office_macro": "Archive contains a macro-enabled Office document.",
    "archive_contains_legacy_office": "Archive contains a legacy Office document.",
    "archive_contains_html": "Archive contains an HTML file (smuggling).",
    "archive_contains_onenote": "Archive contains a OneNote file.",
    "nested_archive": "Archive inside an archive.",
    "archive_single_executable": "Archive whose only file is an executable.",
    "archive_single_lure": "Archive whose only file is a typical lure (html, pdf, lnk, iso...).",
    "zip_bomb": "Decompression bomb.",
    "archive_path_traversal": "Entry names with path traversal.",
    "archive_many_entries": "Archive with hundreds of entries.",
    "archive_corrupt": "Corrupt archive.",
    "unsupported_archive_format": "Archive format not fully parsed (rar/7z/cab): names sniffed only.",
    "disk_image_contains_executable": "Disk image contains an executable.",
    "disk_image_contains_shortcut": "Disk image contains a shortcut.",
    "html_attachment": "HTML attachment (phishing page / smuggling carrier).",
    "html_smuggling": "HTML smuggling: the page reconstructs and drops a file in the browser.",
    "html_smuggling_possible": "Some HTML smuggling techniques present.",
    "html_embedded_payload": "Base64 payload decodes to an executable / archive / document.",
    "html_obfuscated": "Obfuscated HTML/JS.",
    "html_dynamic_code": "eval / Function / unescape usage.",
    "html_event_handler": "Inline event handlers (onload...).",
    "html_password_form": "Login form with a password field.",
    "html_credential_harvest": "Login form posting credentials to an external server.",
    "html_email_form": "Form collecting e-mail addresses.",
    "html_brand_lure": "Page title imitates a brand / sign-in page.",
    "html_prefilled_email": "Victim's e-mail pre-filled in the form.",
    "html_meta_refresh": "Meta-refresh redirect.",
    "html_js_redirect": "JavaScript redirect.",
    "html_hidden_iframe": "Hidden iframe.",
    "svg_script": "SVG with scripts / event handlers.",
    "html_redirect_only": "Tiny page whose only purpose is to redirect.",
    "html_script_only": "Page that is only a script.",
    "html_callback_lure": "Phone number call-back scam.",
    "nested_mail": "Forwarded message attached.",
    "empty_file": "Empty attachment.",
    "large_attachment": "Attachment larger than 25 MB.",
    "yara_match": "Matched a YARA rule.",
    "calendar_lure": "Calendar invitation with links / attendees (calendar phishing).",
    "vcard": "vCard.",
    "analysis_error": "The analyzer raised an error on this file.",
    "office_parse_error": "Office document could not be parsed.",
    "parse_error": "Message could not be parsed.",
}


def describe_flag(flag: str) -> str:
    if flag in FLAGS:
        return FLAGS[flag]
    for prefix in ("att_", "nested_", "archive_entry_", "sender_", "replyto_", "url_"):
        if flag.startswith(prefix) and flag[len(prefix):] in FLAGS:
            return FLAGS[flag[len(prefix):]]
    return flag.replace("_", " ")
