/**
 * The investigative questions a case can be read against (docs/questions.md): scenarios, their
 * facets and their questions, from DFIQ (https://dfiq.org, Apache-2.0, Copyright 2024 Google LLC)
 * and from REMN's own layer (ids starting with 0, the range DFIQ keeps for private content).
 *
 * The catalog is generated by tools/dfiq_import.py from a DFIQ release and tools/dfiq_remn.yaml,
 * and bundled as JSON: nothing is fetched. Each question carries what REMN can use to answer it:
 * the evidence that can (matched against what the case holds, coverage.ts), searches on the
 * Events or Mails page, and the ATT&CK techniques and rule tags that find the related rules.
 */
import type { Rule } from '../../rules/engine'
import type { Filter } from '../../rules/filter'
import raw from './dfiq.gen.json'

/** One kind of evidence a case can hold, matched against the channel and category facets of its events (case-insensitive) and its mails. */
export interface EvidenceKind {
  label: string
  channels?: string[]
  channelPrefixes?: string[]
  categories?: string[]
  categoryPrefixes?: string[]
  mails?: boolean
}

export interface QuestionSearch {
  source: 'events' | 'mails'
  label: string
  filter: Filter
}

/** A DFIQ approach: how the question can be answered with a given tool, and what that way covers and misses. */
export interface Approach {
  id: string
  name: string
  summary: string
  covered: string[]
  notCovered: string[]
}

/** What a question works out from the case itself, beside its searches (coverage.ts derivedFacts). */
export type Derived = 'first-activity' | 'last-activity' | 'log-reach' | 'evidence-gaps'

export interface Question {
  id: string
  origin: 'dfiq' | 'remn'
  name: string
  description: string
  tags: string[]
  /** evidence kinds that can answer it; any one of them is enough */
  evidence: string[]
  attack: string[]
  ruleTags: string[]
  searches: QuestionSearch[]
  note?: string
  derived?: Derived
  approaches: Approach[]
}

export interface Facet {
  id: string
  name: string
  description: string
  tags: string[]
  attack: string[]
  questions: string[]
}

export interface Scenario {
  id: string
  origin: 'dfiq' | 'remn'
  name: string
  description: string
  tags: string[]
  attack: string[]
  facets: string[]
}

export interface Catalog {
  dfiq: { version: string; url: string; repository: string; license: string; copyright: string }
  evidence: Record<string, EvidenceKind>
  scenarios: Scenario[]
  facets: Facet[]
  questions: Question[]
  /** DFIQ questions of the imported scenarios that nothing REMN reads can answer */
  skipped: { id: string; name: string }[]
}

export const CATALOG = raw as unknown as Catalog

const byId = <T extends { id: string }>(items: T[]) => new Map(items.map((i) => [i.id, i]))
export const SCENARIOS = byId(CATALOG.scenarios)
export const FACETS = byId(CATALOG.facets)
export const QUESTIONS = byId(CATALOG.questions)

/** A facet of a chosen scenario, with its questions in order. */
export interface FacetView {
  facet: Facet
  questions: Question[]
}
export interface ScenarioView {
  scenario: Scenario
  facets: FacetView[]
}

/** The chosen scenarios in catalog order, each with its facets and questions; unknown ids are left out. */
export function scenarioViews(ids: string[]): ScenarioView[] {
  const chosen = new Set(ids)
  return CATALOG.scenarios
    .filter((s) => chosen.has(s.id))
    .map((scenario) => ({
      scenario,
      facets: scenario.facets
        .map((fid) => FACETS.get(fid))
        .filter((f): f is Facet => !!f)
        .map((facet) => ({ facet, questions: facet.questions.map((q) => QUESTIONS.get(q)).filter((q): q is Question => !!q) })),
    }))
}

/** Every question of the chosen scenarios once, in order (a facet shared by two scenarios counts once). */
export function questionsOf(ids: string[]): Question[] {
  const seen = new Map<string, Question>()
  for (const s of scenarioViews(ids)) for (const f of s.facets) for (const q of f.questions) if (!seen.has(q.id)) seen.set(q.id, q)
  return [...seen.values()]
}

/** A technique relates to another when one is the other or its parent (T1053 and T1053.005). */
export function techniqueRelated(a: string, b: string): boolean {
  const x = a.toUpperCase()
  const y = b.toUpperCase()
  return x === y || x.startsWith(`${y}.`) || y.startsWith(`${x}.`)
}

/** The rules whose ATT&CK techniques or tags the question names. */
export function relatedRules<T extends { rule: Pick<Rule, 'id' | 'attack' | 'tags'> }>(q: Pick<Question, 'attack' | 'ruleTags'>, rules: T[]): T[] {
  const tags = new Set(q.ruleTags.map((t) => t.toLowerCase()))
  const techniques = q.attack.filter((a) => /^T\d/i.test(a))
  return rules.filter((r) => (r.rule.attack ?? []).some((a) => techniques.some((t) => techniqueRelated(a, t))) || (r.rule.tags ?? []).some((t) => tags.has(t.toLowerCase())))
}
