"""The tables the server's EVTX flattening reads, written out for the in-browser port.

frontend/src/parsers/evtx/reference.gen.ts is generated from backend/services/parsers/evtx_parser.py
and backend/services/reference/eventids.py, so the two parsers map fields, name event ids and
explain status codes from one source. tests/backend/test_evtx_reference_export.py fails when the
generated file is behind the Python tables.

    .venv/bin/python tools/export_evtx_reference.py          # rewrite the file
    .venv/bin/python tools/export_evtx_reference.py --check  # exit 1 when it is out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from services.parsers import evtx_parser as P  # noqa: E402
from services.reference import eventids as E  # noqa: E402

OUT = ROOT / "frontend" / "src" / "parsers" / "evtx" / "reference.gen.ts"


def render() -> str:
    def j(value: object) -> str:
        return json.dumps(value, ensure_ascii=False, indent=2)

    parts = [
        "// Generated by tools/export_evtx_reference.py from the server's EVTX parser and event reference. Do not edit.",
        "",
        f"export const LEVELS: Record<number, string> = {j({str(k): v for k, v in P.LEVELS.items()})}",
        "",
        "/** EventData / UserData field name -> row key, in the server's order */",
        f"export const FIELD_MAP: Record<string, string> = {j(P.FIELD_MAP)}",
        "",
        f"export const GROUP_EVENTS: ReadonlySet<number> = new Set({j(sorted(P._GROUP_EVENTS))})",
        f"export const INT_FIELDS: ReadonlySet<string> = new Set({j(sorted(P._INT_FIELDS))})",
        f"export const LONG_FIELDS: ReadonlySet<string> = new Set({j(sorted(P._LONG_FIELDS))})",
        f"export const LONG_LIMIT = {P.LONG_LIMIT}",
        f"export const ACCESS_NAMES: Record<string, string> = {j(P._ACCESS_NAMES)}",
        "",
        f"export const LOGON_TYPES: Record<number, string> = {j({str(k): v for k, v in E.LOGON_TYPES.items()})}",
        f"export const STATUS_CODES: Record<string, string> = {j(E.STATUS_CODES)}",
        f"export const KERBEROS_FAILURES: Record<string, string> = {j(E.KERBEROS_FAILURES)}",
        f"export const TICKET_ENCRYPTION: Record<string, string> = {j(E.TICKET_ENCRYPTION)}",
        "",
        "/** [provider fragment, event id, description, category], in the server's order: the longest matching fragment wins, the first among equals */",
        f"export const EVENTS: [string, number, string, string][] = {json.dumps([[f, i, d, c] for (f, i), (d, c) in E._EVENTS.items()], ensure_ascii=False)}",
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 when the generated file is out of date")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run tools/export_evtx_reference.py")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
