"""Golden corpus: the rows the server's parsers make of the synthetic lab, frozen.

The quick-start pack of samples/synthetic/make_linked_lab.py is generated byte for byte the same
on every run, so what the parsers make of it can be pinned: for each file, the digest of its input,
the number of rows, a digest over all of them and a short digest of each row, every row written as
canonical JSON (sorted keys, no spaces). A parser change then shows up as the rows it changed, not
as a count that happens to hold, and a later parser (the in-browser port) has an answer to agree
with, row by row. tests/backend/test_golden_corpus.py checks it on every run.

    .venv\\Scripts\\python.exe tools\\golden_corpus.py            # regenerate the lab, compare, list what changed
    .venv\\Scripts\\python.exe tools\\golden_corpus.py --write    # freeze the current rows, after reviewing the change
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "forensic.settings")

GOLDEN = ROOT / "tests" / "fixtures" / "golden" / "lab-quick-start.json.gz"
GENERATOR = ROOT / "samples" / "synthetic" / "make_linked_lab.py"
FILES = [
    "Mailboxes.mbox",
    "Security.evtx",
    "Sysmon.evtx",
    "PowerShell.evtx",
    "System.evtx",
    "Defender.evtx",
    "M365-UnifiedAuditLog.csv",
    "M365-EntraSignIns.jsonl",
]


def canonical(row: dict[str, Any]) -> bytes:
    return (json.dumps(row, sort_keys=True, ensure_ascii=False, separators=(",", ":"), default=str) + "\n").encode("utf-8")


def generate_lab(parent: Path) -> Path:
    out = parent / "lab"  # the generator writes a folder of its own and will not reuse one
    subprocess.run([sys.executable, str(GENERATOR), "--quick-only", "--out", str(out)], check=True, stdout=subprocess.DEVNULL)
    return out / "quick-start"


def parse(lab: Path, name: str, tmp: str) -> list[dict[str, Any]]:
    """The rows the server streams for this file, with the lab's case settings, as an upload gets them."""
    import django

    django.setup()
    from services.ingest.pipeline import EvtxSource, MailSource
    from services.parsers.mail.common import ParseContext

    if name.endswith(".mbox"):
        s = json.loads((lab / "case-settings.json").read_text(encoding="utf-8"))
        ctx = ParseContext(
            internal_domains=list(s.get("internalDomains") or []),
            brands=list(s.get("brands") or []),
            vip_names=list(s.get("vipNames") or []),
            trusted_senders=list(s.get("trustedSenders") or []),
            trusted_arc_sealers=[str(x).lower() for x in (s.get("trustedArcSealers") or [])],
        )
        return list(MailSource(name, str(lab / name), None, ctx, tmp))
    return list(EvtxSource(name, str(lab / name), None, tmp, include_raw=True))


def build(lab: Path) -> dict[str, Any]:
    files: dict[str, Any] = {}
    with tempfile.TemporaryDirectory() as tmp:
        for name in FILES:
            rows = parse(lab, name, tmp)
            whole = hashlib.sha256()
            per_row = []
            for r in rows:
                b = canonical(r)
                whole.update(b)
                per_row.append(hashlib.sha256(b).hexdigest()[:16])
            files[name] = {
                "input": hashlib.sha256((lab / name).read_bytes()).hexdigest(),
                "rows": len(rows),
                "sha256": whole.hexdigest(),
                "rowDigests": per_row,
            }
    return {"corpus": "make_linked_lab.py --quick-only", "canonical": "json, sorted keys, no spaces, one row per line", "files": files}


def load() -> dict[str, Any]:
    return json.loads(gzip.decompress(GOLDEN.read_bytes()))


def differences(golden: dict[str, Any], now: dict[str, Any], lab: Path | None = None) -> list[str]:
    """What changed, file by file: the input (the generator changed), the count, or which rows."""
    out = []
    for name, want in golden["files"].items():
        have = now["files"].get(name)
        if have is None:
            out.append(f"{name}: not parsed")
            continue
        if have["input"] != want["input"]:
            out.append(f"{name}: the lab file itself changed (the generator, not a parser)")
            continue
        if have["sha256"] == want["sha256"]:
            continue
        changed = [i for i, (a, b) in enumerate(zip(want["rowDigests"], have["rowDigests"])) if a != b]
        line = f"{name}: {want['rows']} rows frozen, {have['rows']} now; {len(changed)} row(s) differ"
        if changed:
            line += f", first at row {changed[0]}"
            if lab is not None:
                with tempfile.TemporaryDirectory() as tmp:
                    row = parse(lab, name, tmp)[changed[0]]
                line += f": {canonical(row).decode()[:600]}"
        out.append(line)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="freeze the rows the parsers make now")
    args = ap.parse_args()
    with tempfile.TemporaryDirectory() as out:
        lab = generate_lab(Path(out))
        now = build(lab)
        if args.write:
            GOLDEN.parent.mkdir(parents=True, exist_ok=True)
            GOLDEN.write_bytes(gzip.compress(json.dumps(now, indent=1).encode(), compresslevel=9, mtime=0))
            print(f"wrote {GOLDEN.relative_to(ROOT)}: " + ", ".join(f"{n} {f['rows']}" for n, f in now["files"].items()))
            return 0
        diff = differences(load(), now, lab)
    for line in diff:
        print(line)
    print("the rows match the golden corpus" if not diff else f"{len(diff)} file(s) differ from the golden corpus")
    return 1 if diff else 0


if __name__ == "__main__":
    sys.exit(main())
